export const COMPANY_INFO = {
  name: "Paras Printers",
  tagline: "Premier B2B Manufacturer of PVC & Barcode Labels",
  established: "2014",
  experienceYears: "10+",
  location: "North Guwahati, Assam - 781030, India",
  phonePrimary: "+91 98765 43210",
  phoneSecondary: "+91 361 234 5678",
  email: "sales@parasprinters.com",
  gstin: "18AABCP1234F1Z9",
  indiamartRating: "3.7 / 5.0",
  indiamartTrustYears: "10+ Years Verified",
  responseRate: "61%",
  operatingHours: "Mon - Sat: 9:00 AM - 7:30 PM IST",
  address: "Plot No. 42, Industrial Area, North Guwahati, Kamrup, Assam 781030",
};

export const CATEGORIES = [
  {
    id: "cat-1",
    name: "Custom Labels",
    slug: "custom-labels",
    description: "Bespoke die-cut multi-color roll & sheet labels tailored for brand packaging.",
    iconName: "Tag",
    productCount: 14,
    imageUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "cat-2",
    name: "Barcode Labels",
    slug: "barcode-labels",
    description: "High-density thermal transfer PE & paper labels for logistics and inventory scanner readability.",
    iconName: "QrCode",
    productCount: 22,
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "cat-3",
    name: "Food Labels",
    slug: "food-labels",
    description: "FDA-compliant grease-proof, moisture-resistant labels for food & beverage containers.",
    iconName: "Utensils",
    productCount: 18,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "cat-4",
    name: "Pharmaceutical Labels",
    slug: "pharmaceutical-labels",
    description: "Precision tamper-evident and vial labels meeting strict healthcare standards.",
    iconName: "Pill",
    productCount: 16,
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "cat-5",
    name: "Cosmetic Labels",
    slug: "cosmetic-labels",
    description: "Waterproof metallic foil & clear BOPP labels for luxury beauty products.",
    iconName: "Sparkles",
    productCount: 12,
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "cat-6",
    name: "Industrial Labels",
    slug: "industrial-labels",
    description: "Heavy-duty chemical-resistant vinyl and polyester labels for machinery.",
    iconName: "Factory",
    productCount: 15,
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "cat-7",
    name: "Packaging Labels",
    slug: "packaging-labels",
    description: "Outer carton shipping & corrugated box identification labels.",
    iconName: "Package",
    productCount: 20,
    imageUrl: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "cat-8",
    name: "Security Labels",
    slug: "security-labels",
    description: "Tamper-proof void tamper-evident and holographic security stickers.",
    iconName: "ShieldAlert",
    productCount: 9,
    imageUrl: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=800&auto=format&fit=crop",
  },
];

export const FEATURED_PRODUCTS = [
  {
    id: "prod-1",
    name: "PE Barcode Label Stickers",
    slug: "pe-barcode-label-stickers",
    categoryId: "cat-2",
    categoryName: "Barcode Labels",
    subtitle: "High-Durability Polyethylene Barcode Rolls",
    description: "Industrial grade PE Barcode Label Rolls designed for seamless thermal transfer printing. Resistance to smudged ink, moisture, and tearing make these ideal for warehouse logistics and automated scanners.",
    features: [
      "Smudge-proof thermal transfer coating",
      "High scan accuracy (1D & 2D barcodes)",
      "Strong acrylic adhesive backing",
      "Custom roll inner core options (1-inch & 3-inch)",
    ],
    applications: ["Logistics", "Warehouse Tracking", "Retail Inventory", "Asset Management"],
    materials: ["Polyethylene (PE)", "Glassine Release Paper"],
    minOrderQty: 2000,
    images: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop",
    ],
    isFeatured: true,
    technicalSpecs: {
      "Substrate Material": "Polyethylene Film",
      "Adhesive Type": "Permanent Acrylic Base",
      "Print Compatibility": "Zebra, TSC, Citizen, SATO Thermal Printers",
      "Temperature Range": "-20°C to +80°C",
    },
  },
  {
    id: "prod-2",
    name: "PVC Water Bottle Wrap Labels",
    slug: "pvc-water-bottle-wrap-labels",
    categoryId: "cat-3",
    categoryName: "Food Labels",
    subtitle: "Full-Body Shrink & Roll-Fed PVC Labels",
    description: "Vibrant multi-color printed PVC shrink and wrap-around labels for packaged drinking water bottles. Waterproof construction guarantees zero ink peeling under heavy condensation.",
    features: [
      "Reverse rotogravure printing up to 8 colors",
      "100% moisture & water immersion proof",
      "High gloss or ultra-clear finish",
      "Precise registration for automatic sleeve applicators",
    ],
    applications: ["Mineral Water Bottles", "Beverage Cans", "Edible Oil Jars"],
    materials: ["PVC Shrink Film", "BOPP"],
    minOrderQty: 5000,
    images: [
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop",
    ],
    isFeatured: true,
    technicalSpecs: {
      "Film Thickness": "30 to 50 Microns",
      "Shrink Ratio": "Transverse 50-65%, Longitudinal 0-5%",
      "Printing Method": "High Speed Rotogravure",
    },
  },
  {
    id: "prod-3",
    name: "Pharmaceutical Vial & Bottle Labels",
    slug: "pharmaceutical-vial-bottle-labels",
    categoryId: "cat-4",
    categoryName: "Pharmaceutical Labels",
    subtitle: "Sterile & Tamper-Evident Healthcare Labels",
    description: "Certified pharmaceutical grade labels manufactured under hygienic cleanroom conditions in North Guwahati. Features tight curvature wrap adhesion for small diameter syrup bottles and glass vials.",
    features: [
      "Non-migrating low-toxicity adhesive",
      "Small radius mandrel adhesion (no edge flagging)",
      "Variable serialization & batch coding ready",
      "Tamper-evident break lines",
    ],
    applications: ["Medicine Bottles", "Syrup Vials", "Ointment Tubes", "IV Bags"],
    materials: ["Cast Coated Paper", "White BOPP"],
    minOrderQty: 3000,
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop",
    ],
    isFeatured: true,
    technicalSpecs: {
      "Compliance": "GMP Certified & Drug Grade Adhesive",
      "Core Size": "76mm (3 inches)",
      "Sterilization Safe": "Autoclave & ETO Compatible",
    },
  },
  {
    id: "prod-4",
    name: "Thermal Barcode Ribbons (Wax & Resin)",
    slug: "thermal-barcode-ribbons-wax-resin",
    categoryId: "cat-2",
    categoryName: "Barcode Labels",
    subtitle: "Premium Transfer Ribbons for Barcode Printers",
    description: "High-grade Thermal Transfer Ribbons (Wax, Wax-Resin, and Pure Resin formulations) engineered to produce crisp dark barcodes with minimum printhead wear.",
    features: [
      "Anti-static backcoating protects printhead",
      "Dark dense printing at speeds up to 10 ips",
      "Scratch & solvent resistance (Resin grade)",
      "Universal fit for major printer brands",
    ],
    applications: ["Barcode Printing", "Shipping Tags", "Asset Labels"],
    materials: ["Polyester Ribbon Film", "Wax/Resin Ink"],
    minOrderQty: 20,
    images: [
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=800&auto=format&fit=crop",
    ],
    isFeatured: true,
    technicalSpecs: {
      "Ribbon Types": "Premium Wax, Wax-Resin, Full Resin",
      "Standard Widths": "110mm, 80mm, 60mm",
      "Length": "300 meters / 450 meters",
    },
  },
];

export const MACHINES = [
  {
    id: "m-1",
    name: "Multi-Color Rotary Flexographic Press",
    category: "Flexo Printing",
    capacity: "150,000 labels per hour",
    description: "High-speed multi-color flexo line with inline UV curing, die-cutting, and auto-inspection.",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop",
    specs: {
      "Print Width": "330mm",
      "Colors": "Up to 8 Colors",
      "Curing": "Dual UV & Hot Air",
    },
  },
  {
    id: "m-2",
    name: "Automated Laser & Rotary Die-Cutter",
    category: "Finishing & Slitting",
    capacity: "200 meters/min",
    description: "Precision die-cutting system providing exact dimension accuracy for roll-fed labels.",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=800&auto=format&fit=crop",
    specs: {
      "Accuracy": "± 0.1 mm",
      "Slitting Units": "12 Shear Blades",
    },
  },
  {
    id: "m-3",
    name: "Heavy-Duty Commercial Offset Press",
    category: "Offset Printing",
    capacity: "15,000 sheets/hour",
    description: "Four-color offset sheet press for corporate brochures, folding box cartons, and catalogs.",
    image: "https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?q=80&w=800&auto=format&fit=crop",
    specs: {
      "Max Sheet Size": "720 x 1020 mm",
      "Paper Stock": "80 GSM to 400 GSM",
    },
  },
];

export const TESTIMONIALS = [
  {
    id: "t-1",
    clientName: "Rajesh Sharma",
    company: "Assam Herbal Pharmaceuticals Ltd.",
    industry: "Pharmaceuticals",
    designation: "Supply Chain Manager",
    content: "Paras Printers has been our exclusive label supplier for 6+ years. Their pharmaceutical syrup bottle labels adhere flawlessly and pass every audit.",
    rating: 5,
    verifiedSupplierBadge: true,
  },
  {
    id: "t-2",
    clientName: "Bikash Gogoi",
    company: "NorthEast Aqua Beverages",
    industry: "Packaged Water",
    designation: "Plant Operations Head",
    content: "We print over 2,000,000 water bottle wrap labels monthly with Paras Printers. Crisp print quality, fast delivery, and unbeatable wholesale pricing in Guwahati.",
    rating: 5,
    verifiedSupplierBadge: true,
  },
  {
    id: "t-3",
    clientName: "Ananya Roy",
    company: "Silk & Glow Cosmetics",
    industry: "Cosmetics",
    designation: "Brand & Packaging Director",
    content: "The metallic foil and clear BOPP labels transformed our lotion bottles. Excellent color accuracy and prompt customer service.",
    rating: 5,
    verifiedSupplierBadge: true,
  },
];

export const FAQS = [
  {
    id: "faq-1",
    category: "Orders & MOQ",
    question: "What is the Minimum Order Quantity (MOQ) for custom roll labels?",
    answer: "Our standard minimum order quantity for custom roll barcode & PVC labels is 1,000 to 2,000 units depending on the label size and material specifications.",
  },
  {
    id: "faq-2",
    category: "Materials & Printing",
    question: "Which label materials are best for waterproof or outdoor applications?",
    answer: "For waterproof and outdoor durability, we recommend Polyethylene (PE), Polypropylene (BOPP), or PVC shrink films paired with acrylic adhesives.",
  },
  {
    id: "faq-3",
    category: "Delivery & Logistics",
    question: "Do you ship nationwide across India from North Guwahati?",
    answer: "Yes! We ship nationwide across Northeast India and Pan-India via leading express logistics partners (BlueDart, Delhivery, SafeExpress).",
  },
  {
    id: "faq-4",
    category: "Samples & Quotes",
    question: "Can I request physical label samples before placing a bulk order?",
    answer: "Absolutely. We provide sample test rolls or sample swatch booklets so you can test barcode scanning and adhesion on your actual product containers.",
  },
];
